;;This file autogenerated from 
;;
;;  src/cljx/startlabs/views/job.cljx
;;
^{:cljs true, :line 5} (ns startlabs.views.job ^{:line 6} (:require [singult.core :as s]))
^{:cljs true, :line 9} (defn is-email? [v] ^{:line 10} (re-matches #"(?i)[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" v))
^{:cljs true, :line 14} (def html s/render)
^{:line 16} (defn job-card [job-info] ^{:line 17} (html [:div.thumbnail [:h2 [:a {:href ^{:line 19} (or ^{:line 19} (:website job-info) "#")} ^{:line 19} (:company job-info) ":"] [:small " " ^{:line 20} (:position job-info)]] [:div.row-fluid [:p.span6 [:i.icon.icon-calendar] ^{:line 23} (:start_date job-info) " — " ^{:line 23} (:end_date job-info)] [:p.span6 [:i.icon.icon-map-marker] ^{:line 24} (:location job-info)]] [:div.row-fluid [:p ^{:line 27} (:description job-info)] [:p.well "Contact: " [:i.icon.icon-envelope] ^{:line 31} (let [contact-info ^{:line 31} (:contact_info job-info)] [:a {:href ^{:line 32} (str ^{:line 32} (if ^{:line 32} (is-email? contact-info) "mailto:") contact-info)} contact-info])]]]))