;;This file autogenerated from 
;;
;;  src/cljx/startlabs/views/jobx.cljx
;;
^{:cljs true, :line 7} (ns startlabs.views.jobx ^{:line 8} (:require [singult.core :as s]) ^{:line 9} (:use [c2.core :only [unify]]))
^{:cljs true, :line 12} (defn is-email? [v] ^{:line 13} (re-matches #"(?i)[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" v))
^{:cljs true, :line 16} (def markdownify markdown/mdToHtml)
^{:line 18} (defn is-phone? "Naive, really just checks that the characters are only numbers, digits, dashes, parens, or dots." [v] ^{:line 21} (re-matches #"^[\d-\.\(\)\s]{7,15}$" v))
^{:line 23} (defn is-www? "Checks if site begins with www. (but not http)" [v] ^{:line 26} (not ^{:line 26} (nil? ^{:line 26} (re-find #"^www\." v))))
^{:line 28} (defn linkify "Converts an email address, telephone number, or url into a proper link\n   to be used as the href attribute in an HTML anchor." [text] ^{:line 32} (str ^{:line 33} (condp apply [text] is-email? "mailto:" is-phone? "tel://" is-www? "http://" nil) text))
^{:line 41} (defn job-summary [job-info] [:div.job-summary [:h2 [:a {:href ^{:line 43} (or ^{:line 43} (linkify ^{:line 43} (:website job-info)) "#")} ^{:line 43} (:company job-info) ":"] [:small " " ^{:line 44} (:position job-info)]] [:div.row-fluid.dateloc [:div.span6 [:i.icon.icon-calendar] ^{:line 47} (:start_date job-info) " — " ^{:line 47} (:end_date job-info)] [:div.span6 [:i.icon.icon-map-marker] ^{:line 48} (:location job-info)]]])
^{:line 50} (defn job-card [job-info] [:div.thumbnail.job-info ^{:line 52} (job-summary job-info) [:div.row-fluid [:div.description ^{:line 56} (markdownify ^{:line 56} (:description job-info))] [:div.well.well-small "Contact: " [:i.icon.icon-envelope] ^{:line 61} (let [contact-info ^{:line 61} (:contact_info job-info)] [:a {:href ^{:line 63} (linkify contact-info)} contact-info])]]])
^{:line 67} (defn job-list [jobs] [:ul#job-list.span6 ^{:line 69} (for [job jobs] [:li {:id ^{:line 70} (:id job)} [:a {:href "#"} ^{:line 72} (job-summary job)]])])