;;This file autogenerated from 
;;
;;  src/cljx/startlabs/views/jobx.cljx
;;
^{:cljs true, :line 7} (ns startlabs.views.jobx ^{:line 8} (:require [singult.core :as s]) ^{:line 9} (:use [c2.core :only [unify]]))
^{:cljs true, :line 12} (defn is-email? [v] ^{:line 13} (re-matches #"(?i)[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?" v))
^{:cljs true, :line 16} (def markdownify markdown/mdToHtml)
^{:cljs true, :line 19} (def is-cljs? true)
^{:line 21} (defn is-phone? "Naive, really just checks that the characters are only numbers, digits, dashes, parens, or dots." [v] ^{:line 24} (re-matches #"^[\d-\.\(\)\s]{7,15}$" v))
^{:line 26} (defn is-www? "Checks if site begins with www. (but not http)" [v] ^{:line 29} (not ^{:line 29} (nil? ^{:line 29} (re-find #"^www\." v))))
^{:line 31} (defn linkify "Converts an email address, telephone number, or url into a proper link\n   to be used as the href attribute in an HTML anchor." [text] ^{:line 35} (str ^{:line 36} (condp apply [text] is-email? "mailto:" is-phone? "tel://" is-www? "http://" nil) text))
^{:line 45} (defn job-card [job-info] [:div.thumbnail.job-info [:h2 [:a {:href ^{:line 47} (or ^{:line 47} (linkify ^{:line 47} (:website job-info)) "#")} ^{:line 47} (:company job-info) ":"] [:small " " ^{:line 48} (:position job-info)]] [:div.row-fluid.dateloc [:div.span6 [:i.icon.icon-calendar] ^{:line 51} (:start_date job-info) " — " ^{:line 51} (:end_date job-info)] [:div.span6 [:i.icon.icon-map-marker] ^{:line 52} (:location job-info)]] [:div.row-fluid [:div {:class ^{:line 54} (str "description" ^{:line 54} (if is-cljs? " unrendered"))} ^{:line 55} (markdownify ^{:line 55} (:description job-info))] [:div.well.well-small "Contact: " [:i.icon.icon-envelope] ^{:line 60} (let [contact-info ^{:line 60} (:contact_info job-info)] [:a {:href ^{:line 62} (linkify contact-info)} contact-info])]]])
^{:line 65} (defn job-list [jobs] [:ul#job-list.thumbnails ^{:line 67} (for [job jobs] [:li.job-brick.span6 {:id ^{:line 68} (:id job)} ^{:line 69} (job-card job)])])